concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "7f0766580961"
  url = "https://gitlab.com"
  id = 51488218
  token = "glrt-9MxGJDSh5hYrFUj25y7zaG86MQpwOjFhZ2Robgp0OjMKdTpqcHllORg.01.1j17o2zgh"
  token_obtained_at = 2026-01-27T15:04:20Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:24-dind"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "runner-local-uyoop"
  url = "https://gitlab.com"
  id = 51488218
  token = "glrt-9MxGJDSh5hYrFUj25y7zaG86MQpwOjFhZ2Robgp0OjMKdTpqcHllORg.01.1j17o2zgh"
  token_obtained_at = 2026-01-27T21:52:24Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
